version: '3.8'

services:
  # MongoDB para testes
  mongodb-test:
    image: mongo:latest
    container_name: mongodb-test
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=test_auction_db
    volumes:
      - mongo-test-data:/data/db
    networks:
      - testNetwork
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Serviço para executar todos os testes
  test-all:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGODB_URL=mongodb://mongodb-test:27017
      - MONGODB_DB=test_auction_db
      - AUCTION_INTERVAL=30s
      - AUCTION_CHECK_INTERVAL=5s
      - AUCTION_CONTEXT_TIMEOUT=10s
      - GIN_MODE=test
    command: sh -c "go test ./... -v -cover"
    networks:
      - testNetwork
    depends_on:
      mongodb-test:
        condition: service_healthy

  # Serviço para executar testes específicos do auction
  test-auction:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGODB_URL=mongodb://mongodb-test:27017
      - MONGODB_DB=test_auction_db
      - AUCTION_INTERVAL=30s
      - AUCTION_CHECK_INTERVAL=5s
      - AUCTION_CONTEXT_TIMEOUT=10s
      - GIN_MODE=test
    command: sh -c "go test ./internal/infra/database/auction/ -v -cover"
    networks:
      - testNetwork
    depends_on:
      mongodb-test:
        condition: service_healthy

  # Serviço para executar testes de integração
  test-integration:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGODB_URL=mongodb://mongodb-test:27017
      - MONGODB_DB=test_auction_db
      - AUCTION_INTERVAL=30s
      - AUCTION_CHECK_INTERVAL=5s
      - AUCTION_CONTEXT_TIMEOUT=10s
      - GIN_MODE=test
    command: sh -c "go test ./... -v -cover -tags=integration"
    networks:
      - testNetwork
    depends_on:
      mongodb-test:
        condition: service_healthy

  # Serviço para executar testes de fechamento automático
  test-auto-close:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGODB_URL=mongodb://mongodb-test:27017
      - MONGODB_DB=test_auction_db
      - AUCTION_INTERVAL=2s
      - AUCTION_CHECK_INTERVAL=1s
      - AUCTION_CONTEXT_TIMEOUT=10s
      - GIN_MODE=test
    command: sh -c "go test ./internal/infra/database/auction/ -v -run TestAutoClose -cover"
    networks:
      - testNetwork
    depends_on:
      mongodb-test:
        condition: service_healthy

  # Serviço para executar testes de performance
  test-performance:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGODB_URL=mongodb://mongodb-test:27017
      - MONGODB_DB=test_auction_db
      - AUCTION_INTERVAL=1s
      - AUCTION_CHECK_INTERVAL=500ms
      - AUCTION_CONTEXT_TIMEOUT=5s
      - GIN_MODE=test
    command: sh -c "go test ./internal/infra/database/auction/ -v -run TestConcurrent -cover"
    networks:
      - testNetwork
    depends_on:
      mongodb-test:
        condition: service_healthy

volumes:
  mongo-test-data:
    driver: local

networks:
  testNetwork:
    driver: bridge
